[package]
name = "qusql"
version = "0.1.0"
edition = "2024"
 
[workspace]
resolver = "3"
members = [
    "benchmark",
    "qusql-mysql-test",
    "qusql-mysql",
    "qusql-parse",
    "qusql-type",
    "qusql-type/mariadb_test"
]
