[package]
name = "qusql-mysql-test"
version = "0.1.0"
edition = "2024"

[dependencies]
qusql-mysql = {path = "../qusql-mysql", features = ["cancel_testing", "list_hack"]}
tokio = {version = "1", features=["full"]}
qusql-mysql-type = {path = "../qusql-mysql-type", features = ["list_hack"]}
